apps/cart/urls.py
from django.urls import path, re_path
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
	path('add/', CartAddView.as_view(), name='add'),
	path('info/', CartInfoView.as_view(), name='info'),
	path('update/', CartUpdateView.as_view(), name='update'),
	path('delete/', CartDeleteView.as_view(), name='delete'),
]

apps/goods/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
	path('index/', IndexView.as_view(), name='index'),
	re_path(r'goods/(?P<goods_id>[0-9]+)$', DetailView.as_view(), name='detail'),
	re_path(r'list/(?P<type_id>[0-9]+)/(?P<page>[0-9]+)', ListView.as_view(), name='list'),

]

apps/order/urls.py
from django.urls import path, re_path
from order.views import OrderPlaceView, OrderCommitView, OrderPayView, OrderCheckView, OrderCommentView

urlpatterns = [
	path('place/', OrderPlaceView.as_view(), name='place'),
	path('commit/', OrderCommitView.as_view(), name='commit'),
	path('pay/', OrderPayView.as_view(), name='pay'),
	path('check/', OrderCheckView.as_view(), name='check'),
	re_path('comment/(?P<order_id>[0-9]+)', OrderCommentView.as_view(), name='comment'),
]

apps/user/urls.py
from django.urls import path, re_path
from user.views import RegisterView, ActiveView, LoginView, UserOrderView, UserInfoView, UserAddressView, LogOutView

urlpatterns = [
	path('register/', RegisterView.as_view(), name='register'),
	re_path('^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogOutView.as_view(), name='logout'),
	path('', UserInfoView.as_view(), name='user'),
	re_path('order/(?P<page>[0-9]+)', UserOrderView.as_view(), name='order'),
	path('address/', UserAddressView.as_view(), name='address'),
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')), # 富文本编辑器
    path('search/', include('haystack.urls')), # 全文检索框架
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    re_path(r'^', include(('goods.urls', 'goods'), namespace='goods')), # 匹配商品模块(不加前缀并且由于匹配顺序放置在末端)
]
# 注意include()中元组

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from django.views import View
from django.urls import reverse
from django.http import JsonResponse
from django_redis import get_redis_connection
from goods.models import GoodsSKU
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin

# 前端采用ajax post传递参数，传递商品id(sku_id),商品数量(count)，并接收Json对象
class CartAddView(View):
	'''添加购物车记录'''
	def post(self, request):
		# 判断用户是否登录
		user = request.user
		if not user.is_authenticated:
			return JsonResponse({'res':0, 'errmsg':'请先登录'})

		# 接收数据，用post方法因此不在定义函数中以形参出现
		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')

		# 校验数据合法性
		if not all([sku_id, count]):
			return JsonResponse({'res':1, 'errmsg':'数据不完整'})
		# 校验商品数量合法性
		try:
			count = int(count)
		except Exception:
			return JsonResponse({'res':2, 'errmsg':'数目出错'})
		# 校验商品是否存在
		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res':3, 'errmsg':'商品不存在'})
		# 添加到购物车，链接到redis数据库
		conn = get_redis_connection('default')
		cart_key = 'cart_{}'.format(user.id)
		# 检索该商品是否已存在，若sku_id在此hash中不存在则返回None
		cart_count = conn.hget(cart_key, sku_id)
		if cart_count:
			count += int(cart_count)
		# 校验库存值，设置对应值
		if count>sku.stock:
			return JsonResponse({'res':4, 'errmsg':'商品库存不足'})
		conn.hset(cart_key, sku_id, count)

		# 计算用户当前购物车条目数
		total_count = conn.hlen(cart_key)

		return JsonResponse({'res':5, 'message':'添加成功', 'total_count':total_count})


class CartInfoView(LoginRequiredMixin, View):
	'''购物车页面显示'''
	def get(self, request):
		# 获取用户购物车中商品的信息
		user = request.user
		conn = get_redis_connection('default')
		cart_key = 'cart_{}'.format(user.id)
		# 从数据库中获取购物车字典，{商品id1:数量, 商品id2:数量}
		cart_dict = conn.hgetall(cart_key)
		skus = list()
		total_count = 0
		total_price = 0
		for sku_id, count in cart_dict.items():
			# 根据商品id获取商品信息
			sku = GoodsSKU.objects.get(id=sku_id)
			# 计算商品的小计价格
			amount = sku.price*int(count)
			# 动态为sku增加属性,小计和数量,并添加到列表中
			sku.amount = amount
			sku.count = int(count)
			skus.append(sku)
			total_count += int(count)
			total_price += amount
		# 组织模板上下文
		context = {
			'skus': skus,
			'total_price': total_price,
			'total_count': total_count,
		}

		return render(request, 'cart.html', context)

# 购物车中数据的更新，因为是ajax post请求，不能使用LoginRequiredMixin，无法跳转
# /cart/update
class CartUpdateView(View):
	'''购物车记录更新'''
	def post(self, request):
		# 判断用户是否登录
		user = request.user
		if not user.is_authenticated:
			return JsonResponse({'res':0, 'errmsg':'请先登录'})
		# 接收数据
		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')
		# 校验数据合法性
		if not all([sku_id, count]):
			return JsonResponse({'res':1, 'errmsg':'数据不完整'})
		# 校验商品数量合法性
		try:
			count = int(count)
		except Exception:
			return JsonResponse({'res':2, 'errmsg':'数目出错'})
		# 校验商品是否存在
		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res':3, 'errmsg':'商品不存在'})
		# 更新redis数据库中记录
		conn = get_redis_connection('default')
		cart_key = 'cart_{}'.format(user.id)
		# 校验库存值，设置对应值
		if count>sku.stock:
			return JsonResponse({'res':4, 'errmsg':'商品库存不足'})
		conn.hset(cart_key, sku_id, count)
		# 更新商品的总件数
		vals = conn.hvals(cart_key)
		total_count = sum([int(x) for x in vals])

		# 返回应答
		return JsonResponse({'res':5, 'total_count':total_count, 'message':'更新成功'})

# /cart/delete
class CartDeleteView(View):
	'''购物车记录删除'''
	def post(self, request):
		# 判断用户是否登录
		user = request.user
		if not user.is_authenticated:
			return JsonResponse({'res':0, 'errmsg':'请先登录'})
		# 接收数据
		sku_id = request.POST.get('sku_id')
		# 数据校验
		if not sku_id:
			return JsonResponse({'res':1, 'errmsg':'无效的商品ID'})
		# 校验商品是否存在
		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res':2, 'errmsg':'商品不存在'})
		# 更新redis数据库中记录
		conn = get_redis_connection('default')
		cart_key = 'cart_{}'.format(user.id)
		conn.hdel(cart_key, sku_id)
		# 更新商品的总件数
		vals = conn.hvals(cart_key)
		total_count = sum([int(x) for x in vals])
		# 返回应答
		return JsonResponse({'res':3, 'total_count':total_count, 'message':'删除成功'})

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
{# 网页标题块，统一不加标签 #}
{% block title %}{% endblock title %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{# 网页顶部引入文件块 #}
{% block topfiles %}
{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block head_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock head_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}
{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}

{# 网页底部引入文件块 #}
{% block bottomfiles %}
{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页#}
{% extends 'base.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	{% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心3页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}
<title>天天生鲜-用户中心</title>
{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" 
					{% if page == 'user' %} 
					class="active" 
					{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}"
					{% if page == 'order' %} 
					class="active" 
					{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}"
					{% if page == 'address' %} 
					class="active" 
					{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		{# 用户中心右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
		<div style="clear:both;"></div>
	</div>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}

<title>天天生鲜-首页</title>
{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
			
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for goods_banner in goods_banners %}
				<li><a href="{% url 'goods:detail' goods_banner.sku.id %}"><img src="{{ goods_banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for banner in promotion_banners %}
				<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}
	<title>天天生鲜-商品列表</title>
{% endblock title %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type_current.id 1 %}">{{ type_current.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="#">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type_current.id 1 %}?sort={{ sort }}" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
				<a href="{% url 'goods:list' type_current.id 1 %}?sort=price" {% if sort == 'price' %} class="active" {% endif %}>价格</a>
				<a href="{% url 'goods:list' type_current.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if skus_page.has_previous %}
					<a href="{% url 'goods:list' type_current.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
				{% endif %}

				{% for pindex in pages %}
					{% if pindex == skus_page.number %}
						<a href="{% url 'goods:list' type_current.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="{% url 'goods:list' type_current.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}

				{% if skus_page.has_next %}
					<a href="{% url 'goods:list' type_current.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}
	<title>天天生鲜-提交订单</title>
{% endblock title %}
{% block page_title %}提交订单{% endblock page_title %}
{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			{% for addr in addrs %}
			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked{% endif %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
			{% endfor %}
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>			
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}</li>	
		</ul>
		{% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		{% csrf_token %}
		<a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>	

{% endblock body %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			// 获取用户选择的地址ID，支付方式，商品ID
			addr_id = $('input[name="addr_id"]:checked').val();
			pay_method = $('input[name="pay_style"]:checked').val();
			sku_ids = $(this).attr('sku_ids');
			csrf = $("input[name='csrfmiddlewaretoken']").val();
			params = {'addr_id': addr_id, 'pay_method': pay_method, 'sku_ids': sku_ids, 'csrfmiddlewaretoken': csrf};
			// 发起ajax post请求
			$.post('/order/commit/', params, function(data){
				if (data.res == 6){
					//创建成功
					localStorage.setItem('order_finish',2);
					$('.popup_con').fadeIn('fast', function() {setTimeout(function(){
						$('.popup_con').fadeOut('fast',function(){
						window.location.href = "{% url 'user:order' 1 %}";
						});	
				},3000)
				
			});
				}
				else{
					alert(data.errmsg)
				}
			});

		});
	</script>
{% endblock bottomfiles %}

templates/user_center_order.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
	<div class="right_content clearfix">
			<h3 class="common_title2">全部订单</h3>
			{% for order in order_page %}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{ order.create_time }}</li>
				<li class="col02">订单号：{{ order.order_id }}</li>
				<li class="col02 stress">{{ order.status_name }}</li>		
			</ul>
			{% csrf_token %}
			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							{% for order_sku in order.order_skus %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><a href="{% url 'goods:detail' order_sku.sku.id %}"><img src="{{ order_sku.sku.image.url }}"></a></li>
								<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>	
								<li class="col03">{{ order_sku.count }}</li>
								<li class="col04">{{ order_sku.amount }}元</li>	
							</ul>
							{% endfor %}
						</td>
						<td width="15%">{{ order.total_amount }}（含运费{{ order.transit_price }}）元</td>
						<td width="10%">{{ order.status_name }}</td>
						<td width="10%">{{ order.pay_method_name }}</td>
						<td width="10%"><a href="#" status="{{ order.order_status }}" order_id="{{ order.order_id }}" pay_method="{{ order.pay_method }}" class="oper_btn">去付款</a></td>
					</tr>
				</tbody>
			</table>
			{% endfor %}
			<div class="pagenation">
				{% if order_page.has_previous %}
				<a href="{% url 'user:order' order_page.previous_page_number %}"><上一页</a>
				{% endif %}
				{% for pindex in pages %}
					{% if pindex == order_page.number %}
						<a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}
				{% if order_page.has_next %}
				<a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
				{% endif %}
			</div>
	</div>
{% endblock right_content %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		//查询订单交易状态，更新按钮文字
		$('.oper_btn').each(function(){
			status = $(this).attr('status');
			if (status == 1){
				$(this).text('待支付')
			}
			else if (status == 2){
				$(this).text('待发货')
				$(this).prop('class', null)
			}
			else if (status == 4){
				$(this).text('评价')
			}
			else if (status == 5){
				$(this).text('已完成')
				$(this).prop('class', null)
			}
		});
		$('.oper_btn').click(function(){
			//获取订单的支付状态
			status = $(this).attr('status');
			order_id = $(this).attr('order_id');
			csrf = $("input[name='csrfmiddlewaretoken']").val();
			if (status==1){
				//进行支付
				//发起ajax post请求，访问/order/pay
				params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf};
				$.post('/order/pay/', params, function(data){
					if (data.res==3){
						//引导用户去支付页面
						window.open(data.pay_url)
						//浏览器访问/order/check，获取支付结果
						//发起ajax post请求，由于订单ID可唯一标识订单，因此只需要传递订单ID一个参数
						$.post('/order/check/', params, function(data){
							//获取支付是否成功
							if (data.res==3){
								alert(data.message)
								//刷新页面
								location.reload()
							}
							else{alert(data.errmsg)}
						});
					}
					else{alert(data.errmsg)}
				});
			}
			else if (status==4) {
				//去评论
				location.assign('/order/comment/'+order_id)
			}
		});
	</script>
{% endblock bottomfiles %}

templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_content %}
	<div class="right_content clearfix">
			<h3 class="common_title2">收货地址</h3>
			<div class="site_con">
				<dl>
					<dt>当前地址：</dt>
					{% if address %}
					<dd>{{ address.addr }} {{ address.receiver }} (收) {{ address.phone }}</dd>
					{% else %}
					<dd>无默认收货地址</dd>
					{% endif %}
				</dl>					
			</div>
			<h3 class="common_title2">编辑地址</h3>
			<div class="site_con">
				<form method="post">
					{% csrf_token %}
					<div class="form_group">
						<label>收件人：</label>
						<input type="text" name="receiver">
					</div>
					<div class="form_group form_group2">
						<label>详细地址：</label>
						<textarea class="site_area" name="addr"></textarea>
					</div>
					<div class="form_group">
						<label>邮编：</label>
						<input type="text" name="zipcode">
					</div>
					<div class="form_group">
						<label>手机：</label>
						<input type="text" name="phone">
					</div>

					<input type="submit" value="提交" class="info_submit">
					<p>{{ errmsg }}</p>
				</form>
			</div>
	</div>
{% endblock right_content %}